### ISSUE TITLE
A few files in the wrong place

### ISSUE THREAD

**Issue by 1944GPW** [kgober/VT05#1]
I cloned and built it with VS2017 but some things just needed to be moved to the right place for the Project to build. These were: move Resources.*, Settings.* and AssemblyInfo.cs into the Properties folder (which was empty to start with).  It then built and ran fine. I haven't tested its comms yet but the font and underline cursor really looks retro! Well done.

**Comment by 1944GPW** [comment]
Formatting ate the asterisks I put in. That is meant to be Resources.(star) and Settings.(star) as well as the AssemblyInfo.

**Comment by kgober** [comment]
Thanks, I will fix this.  They were of course originally in the correct places; the directory structure got flattened unintentionally when I did the import into github.

**Comment by kgober** [comment]
This is fixed in the master branch, but I'll leave this issue open until the next release.

**Comment by kgober** [comment]
fix included in release v1.0.0.1
