### ISSUE TITLE
Socket exception for non-connection

### ISSUE THREAD

**Issue by 1944GPW** [kgober/VT05#2]
Probably could do with a bit of trycatchyness around 'new TcpClient(..)' in Telnet Connect(), to absorb the SocketException when connecting to a nonexistent address, eg. with nothing at the receiving end of 127.0.0.1 23.

**Comment by kgober** [comment]
I've seen the same problem when a hostname failed DNS name resolution.  I'll add it to the to-do list.

**Comment by kgober** [comment]
This is fixed in v1.0.0.4
